Repository TeamBeMyPlan/BeMyPlan-Server, pull requests merged in 2022-01, with the labels that each got.

#3 [#2] Sequelize 설정
  .gitignore
  .idea/.gitignore
  .idea/BeMyPlan-Server.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  functions/api/index.js
  functions/api/routes/index.js
  functions/config/dbConfig.js
  functions/controller/index.js
  functions/db/db.js
  functions/db/index.js
  functions/index.js
  functions/loaders/connect.js
  functions/loaders/sequelize.js
  functions/models/index.js
  functions/package-lock.json
  functions/package.json
Labels: chore, 🐮준영

#7 [#6] 데이터베이스 모델 클래스 작성
  functions/models/area.js
  functions/models/index.js
  functions/models/order.js
  functions/models/post.js
  functions/models/scrap.js
  functions/models/spot.js
  functions/models/spot_photo.js
  functions/models/user.js
Labels: 🐮준영, database

#8 [#4] 인기 여행후기 컨텐츠 조회 기능
  functions/api/index.js
  functions/api/routes/index.js
  functions/api/routes/postApi.js
  functions/constants/responseMessage.js
  functions/constants/statusCode.js
  functions/controller/index.js
  functions/controller/postController.js
  functions/lib/util.js
  functions/service/index.js
  functions/service/postService.js
Labels: 🐮준영, feat, 일정조회

#9 [#5] 최신 여행 후기 조회 구현
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/service/postService.js
Labels: 🐱제준, feat, 일정조회

#14 [FEAT] 추천 여행후기 컨텐츠 조회 기능
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/service/postService.js
Labels: 🐱제준, feat, 일정조회

#18 [#15] 여행지 리스트 조회 기능
  functions/api/routes/areaApi.js
  functions/api/routes/index.js
  functions/controller/areaController.js
  functions/controller/index.js
  functions/service/areaService.js
  functions/service/index.js
Labels: 🐱제준, feat, 여행지

#20 [#19] 여행지별 여행후기 컨텐츠 조회 API 구현
  .idea/dataSources/2e95e226-109d-48e1-b2e9-ba3a6355facb.xml
  .idea/dataSources/2e95e226-109d-48e1-b2e9-ba3a6355facb/storage_v2/_src_/database/postgres.edMnLQ/schema/public.abK9xQ.meta
  functions/api/routes/areaApi.js
  functions/controller/areaController.js
  functions/controller/index.js
  functions/lib/pagination.js
  functions/service/areaService.js
Labels: 🐮준영, feat, 일정조회, 여행지

#24 [#21] 여행지별 컨텐츠 미리보기 태그정보 조회
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/service/postService.js
Labels: 🐮준영, feat, 미리보기, 여행컨텐츠

#26 [#21] 여행지별 미리보기 컨텐츠 내용 조회 구현
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/models/spot.js
  functions/service/postService.js
Labels: 🐮준영, feat, 여행지, 미리보기

#27 [#22] 구매한 컨텐츠 조회 기능
  functions/api/routes/index.js
  functions/api/routes/orderApi.js
  functions/controller/index.js
  functions/controller/orderController.js
  functions/models/index.js
  functions/service/index.js
  functions/service/orderService.js
Labels: 🐱제준, feat, 구매

#39 [FEAT] 스크랩 정렬 기능 추가
  functions/controller/scrapController.js
  functions/service/scrapService.js
Labels: 🐱제준, feat, 스크랩

#40 [#30] 여행후기 컨텐츠 상세조회 API 구현
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/service/postService.js
Labels: 🐮준영, feat, 일정조회, 여행컨텐츠

#41 [FEAT] 스크랩 추가 기능 구현
  functions/api/routes/scrapApi.js
  functions/controller/scrapController.js
  functions/service/scrapService.js
Labels: 🐱제준, feat, 스크랩

#42 [#13] 컨텐츠 조회 API 페이징 기능 추가
  functions/controller/postController.js
  functions/service/postService.js
Labels: 🐱제준, feat, 일정조회

#48 [ADD] 페이징 파라미터 defaultValue 설정과 API 리턴값 필드 추가
  .idea/dataSources/2e95e226-109d-48e1-b2e9-ba3a6355facb.xml
  .idea/dataSources/2e95e226-109d-48e1-b2e9-ba3a6355facb/storage_v2/_src_/database/postgres.edMnLQ/schema/public.abK9xQ.meta
  functions/api/routes/scrapApi.js
  functions/controller/areaController.js
  functions/controller/postController.js
  functions/controller/scrapController.js
  functions/service/areaService.js
  functions/service/postService.js
  functions/service/scrapService.js
Labels: 🐮준영, refactor

#50 [FEAT] 스크랩 여부 판단 후 스크랩/스크랩취소 분기처리하는 기능 구현
  functions/api/routes/scrapApi.js
  functions/controller/scrapController.js
  functions/service/postService.js
  functions/service/scrapService.js
Labels: 🐮준영, feat, 스크랩

#52 [#51] 유저별로 작성한 컨텐츠 확인할 수 있는 기능
  functions/api/routes/index.js
  functions/api/routes/orderApi.js
  functions/api/routes/postApi.js
  functions/api/routes/userApi.js
  functions/controller/index.js
  functions/controller/orderController.js
  functions/controller/postController.js
  functions/controller/userController.js
  functions/service/index.js
  functions/service/orderService.js
  functions/service/postService.js
  functions/service/userService.js
Labels: feat, 여행컨텐츠, 유저

#56 [FEAT] 스크랩뷰 랜덤 포스트 기능 추가
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/service/postService.js
Labels: 🐱제준, feat, 스크랩

#57 [#53] 소셜 로그인(카카오) 기능 구현
  .idea/dataSources/2e95e226-109d-48e1-b2e9-ba3a6355facb.xml
  .idea/dataSources/2e95e226-109d-48e1-b2e9-ba3a6355facb/storage_v2/_src_/database/postgres.edMnLQ/schema/public.abK9xQ.meta
  functions/api/routes/authApi.js
  functions/api/routes/index.js
  functions/controller/authController.js
  functions/controller/index.js
  functions/models/user.js
  functions/package-lock.json
  functions/package.json
  functions/service/authService.js
  functions/service/index.js
  functions/utils/KakaoAuth.js
Labels: 🐮준영, feat, 로그인

#58 [#53] 소셜 로그인 반환값에 created 필드 추가 (회원가입 여부)
  functions/service/authService.js
Labels: 🐮준영, feat, 로그인

#63 [FEAT] 스크랩 랜덤 is_purchared 추가
  functions/api/routes/postApi.js
  functions/controller/postController.js
  functions/package-lock.json
  functions/package.json
  functions/service/postService.js
Labels: 🐱제준, feat, 스크랩

#64 [ADD] 스크랩/스크랩취소 API 반환값에 scrapped 필드 추가 (#62)
  functions/service/scrapService.js
Labels: 🐮준영, 스크랩, add

#68 [#53] 소셜 로그인/회원가입 로직을 별도로 분리하여 처리
  functions/api/routes/authApi.js
  functions/constants/responseMessage.js
  functions/controller/authController.js
  functions/lib/util.js
  functions/service/authService.js
Labels: 🐮준영, feat, 로그인

#67 [FEAT] 최신순, 구매순, 추천순, 여행지 리스트 조회 기능 스크랩/구매 여부 추가 구현
  functions/api/routes/postApi.js
  functions/controller/areaController.js
  functions/controller/postController.js
  functions/controller/userController.js
  functions/models/index.js
  functions/service/areaService.js
  functions/service/postService.js
  functions/service/userService.js
Labels: 🐱제준, feat, 일정조회, 여행지

#70 [FEAT] 스크랩뷰 구매여부 기능 추가
  functions/service/scrapService.js
Labels: 🐱제준, feat, 스크랩

#72 [FEAT] 여행지 리스트 뷰, 유저 리스트 뷰 정렬 기준 추가
  functions/service/areaService.js
  functions/service/userService.js
Labels: 🐱제준, feat, 정렬

#74 [FEAT] 가격 필요한 뷰들 가격 컬럼 추가
  functions/service/postService.js
  functions/service/scrapService.js
  functions/service/userService.js
Labels: 🐱제준, feat

#80 [FIX] 스크랩 데이터가 존재하지 않을 때 스크랩 버튼을 누른 경우 데이터 생성
  functions/package-lock.json
  functions/service/scrapService.js
Labels: 🐮준영, 스크랩, fix

#82 [#81] 닉네임 중복체크 로직 작성
  functions/api/routes/authApi.js
  functions/controller/authController.js
  functions/service/authService.js
Labels: 🐮준영, feat
